### ISSUE TITLE
Create new screen of service changes

### ISSUE THREAD

**Issue by KristoferBorges** [KristoferBorges/Python-Exercises#7]
**Desenvolva a nova tela de alterações para serviço, use como base a tela de alterações de clientes mantendo suas semelhanças**

![Image](https://github.com/KristoferBorges/Python-Exercises/assets/40279965/adccf012-6a0e-44aa-8e76-4a04c7a60d79)

**Comment by KristoferBorges** [comment]
**Tela de alteração de serviço criada e testada**



![Image](https://github.com/KristoferBorges/Python-Exercises/assets/40279965/dc0d0270-4f0d-480f-8083-a450342f0be7)


**Arquivo.py**
```python
from kivy.uix.screenmanager import Screen
from app.support.setup import System_Crud
from app.support.modulo import FunctionsCase

class AlterarService(Screen):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.system_crud = System_Crud()
        self.data_from_database = None
        self.dependencia = None

    def mostrarIconSemDependencia(self):
        """
        Método responsável por mostrar o ícone de check
        """
        self.ids.icon_sem_dependencia.opacity = 1
        self.ids.icon_com_dependencia.opacity = 0
        self.dependencia = False

        return self.dependencia
    def mostrarIconComDependencia(self):
        """
        Método responsável por mostrar o ícone de check
        """
        self.ids.icon_sem_dependencia.opacity = 0
        self.ids.icon_com_dependencia.opacity = 1
        self.dependencia = True

        return self.dependencia
    
    def consultarServico(self):
        """
        Método responsável por consultar um serviço
        """
        try:
            if self.system_crud.read_ID_service(self.ids.id_servico.text) == False:
                # Pop-up de erro de preenchimento
                FunctionsCase.popup_id_nao_encontrado()

            else:
                self.data_from_database = self.system_crud.read_ID_service(self.ids.id_servico.text)

                # Preenchendo os campos com os dados do serviço
                self.ids.nome_servico.text = self.data_from_database[0][1]
                self.ids.valor_servico.text = str(self.data_from_database[0][2])
                dependencia = self.data_from_database[0][3]
                if dependencia == "DP":
                    self.mostrarIconComDependencia()
                elif dependencia == "Regular":
                    self.mostrarIconSemDependencia()
                else:
                    pass

                # Libera os campos para edição
                self.ids.id_servico.readonly = True
                self.ids.nome_servico.readonly = False
                self.ids.valor_servico.readonly = False
                self.ids.btn_sem_dependencia.disabled = False
                self.ids.btn_com_dependencia.disabled = False

        except Exception as erro:
            print(f"Exceção alterarService: {erro}")

    def finalizarAlteracao(self):
        """
        Método responsável por finalizar a alteração do serviço no banco de dados.
        """
        try:
            if self.ids.nome_servico == "" or self.ids.valor_servico == "" or self.dependencia == None:
                # Pop-up de erro de preenchimento
                FunctionsCase.popup_preenchimento()
            else:
                # Verifica/Formata informações
                self.ids.nome_servico.text = self.ids.nome_servico.text.upper()
                self.ids.valor_servico.text = self.ids.valor_servico.text.replace(",", ".")
                if self.dependencia == True:
                    self.dependencia = "DP"
                else:
                    self.dependencia = "Regular"

                if self.ids.nome_servico.text == "" or self.ids.valor_servico.text == "" or self.dependencia == None:
                    # Pop-up de erro de preenchimento
                    FunctionsCase.popup_preenchimento()

                else:
                    if self.system_crud.update_service(self.ids.id_servico.text, self.ids.nome_servico.text, self.ids.valor_servico.text, self.dependencia) == True:
                        FunctionsCase.popup_alteracao_sucesso()
                        self.ids.id_servico.text = ""
                        self.ids.nome_servico.text = ""
                        self.ids.valor_servico.text = ""
                        self.ids.icon_sem_dependencia.opacity = 0
                        self.ids.icon_com_dependencia.opacity = 0

                        # Bloqueia os campos para edição
                        self.ids.id_servico.readonly = False
                        self.ids.nome_servico.readonly = True
                        self.ids.valor_servico.readonly = True
                        self.ids.btn_sem_dependencia.disabled = True
                        self.ids.btn_com_dependencia.disabled = True
                    else:
                        FunctionsCase.popup_change_error(self.system_crud.error)
                        self.ids.id_servico.text = ""
                        self.ids.nome_servico.text = ""
                        self.ids.valor_servico.text = ""
                        self.ids.icon_sem_dependencia.opacity = 0
                        self.ids.icon_com_dependencia.opacity = 0

                        # Bloqueia os campos para edição
                        self.ids.id_servico.readonly = False
                        self.ids.nome_servico.readonly = True
                        self.ids.valor_servico.readonly = True
                        self.ids.btn_sem_dependencia.disabled = True
                        self.ids.btn_com_dependencia.disabled = True

        except Exception as erro:
            print(f"Exceção alterarServico: {erro}")
``` 

**Arquivo.kv**

```
<AlterarService>

    Image:
        source: "app/support/image/minimalbackground.jpg"
        allow_stretch: True
        keep_ratio: False
        opacity: 0.060

    MDBoxLayout:
        orientation: "horizontal"

        AnchorLayout:
            anchor_x: "left"
            anchor_y: "top"

            MDRectangleFlatIconButton:
                text: "Back"
                font_name: app.font_monofonto
                icon: "arrow-left"
                theme_text_color: "Custom"
                font_size: "20dp"
                line_color: 0, 0, 0, 0
                on_release: 
                    root.manager.current = "tela_principal"
    
    MDBoxLayout:
        orientation: "horizontal"
        spacing: dp(20)
        padding: dp(20)
        pos_hint: {"center_x": .5, "center_y": .9}

        MDLabel:
            text: "[u]ALTERAR SERVIÇO[/u]"
            font_style: "H5"
            text_color: 1, 1, 1, 1
            font_name: app.font_monofonto
            markup: True
    
    MDGridLayout:
        cols: 1
        adaptive_height: True
        spacing: dp(60)
        padding: dp(23)
        pos_hint: {"center_x": .5, "center_y": .58}

        MDGridLayout:
            cols: 2
            spacing: dp(20)
        
            MDTextField:
                id: id_servico
                name: "id_servico"
                required: True
                hint_text: "ID *"
                mode: "rectangle"
                size_hint_x: 0.65
                hint_text_color_focus: "white"
                strip: True
                font_name: app.font_monofonto
                input_filter: "int"
                multiline: False

            MDRoundFlatIconButton:
                text: "Buscar Serviço"
                icon: "account-search"
                font_name: app.font_monofonto
                text_color: 1, 1, 1, 1
                font_size: "15dp"
                size_hint_x: 0.32
                on_release:
                    root.consultarServico()
                    
        MDBoxLayout:
            orientation: "vertical"
            spacing: dp(20)
            adaptive_height: True

            MDTextField:
                id: nome_servico
                name: "nome_servico"
                hint_text: "Serviço"
                mode: "rectangle"
                size_hint_x: 0.65
                hint_text_color_focus: "white"
                strip: True
                font_name: app.font_monofonto
                multiline: False
                readonly: True
            
            MDTextField:
                id: valor_servico
                name: "valor_servico"
                hint_text: "Valor"
                mode: "rectangle"
                size_hint_x: 0.65
                hint_text_color_focus: "white"
                strip: True
                font_name: app.font_monofonto
                input_filter: "float"
                multiline: False
                readonly: True
            
        MDBoxLayout:
            orientation: 'vertical'
            spacing: "10dp"
            adaptive_height: True

            MDRectangleFlatIconButton:
                id: btn_sem_dependencia
                name: "btn_sem_dependencia"
                text: "SEM DEPENDÊNCIA"
                font_name: app.font_monofonto
                font_size: "20dp"
                text_color: 1, 1, 1, 1
                md_bg_color: .1, .1, .1, 0.90
                line_color: 0, 0, 0, 0
                size_hint_x: 0.65
                width: "120dp"
                disabled: True
                on_release:
                    root.mostrarIconSemDependencia()

                AnchorLayout:
                    anchor_x: "left"
                    anchor_y: "center"

                    MDIcon:
                        id: icon_sem_dependencia
                        name: "icon_sem_dependencia"
                        icon: 'check'
                        opacity: 0
                        theme_text_color: "Custom"
                        text_color: 0, 1, 0, 1

            MDRectangleFlatIconButton:
                id: btn_com_dependencia
                name: "btn_com_dependencia"
                text: "COM DEPENDÊNCIA"
                font_name: app.font_monofonto
                font_size: "20dp"
                text_color: 1, 1, 1, 1
                md_bg_color: .1, .1, .1, 0.90
                line_color: 0, 0, 0, 0
                size_hint_x: 0.65
                width: "120dp"
                disabled: True
                on_release:
                    root.mostrarIconComDependencia()
                
                AnchorLayout:
                    anchor_x: "left"
                    anchor_y: "center"

                    MDIcon:
                        id: icon_com_dependencia
                        name: "icon_com_dependencia"
                        icon: 'check'
                        opacity: 0
                        theme_text_color: "Custom"
                        text_color: 0, 1, 0, 1
    
    MDBoxLayout:
        orientation: "horizontal"
        spacing: dp(20)
        padding: dp(20)

        AnchorLayout:
            anchor_x: "right"
            anchor_y: "bottom"

            MDRoundFlatIconButton:
                text: "FINALIZAR"
                icon: "check"
                size_hint: (0.1, 0.06)
                font_name: app.font_monofonto
                line_color: 0, 0, 0, 0
                font_size: "20dp"
                on_release:
                    root.finalizarAlteracao()
```
